name: 🚚 Extra

on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

jobs:
  setenv:
    runs-on: windows-latest
    outputs:
      service_env: ${{ steps.envmatrix.outputs.service_env }}
    steps:
      - name: 🔸 Output environment matrix
        id: envmatrix
        run: |
          # TODO: Update service_env
          # echo "service_env=${{ github.ref_name == 'master' && vars.SERVICE_ENV_RELEASE || vars.SERVICE_ENV_TEST }}" >> $env:GITHUB_OUTPUT
          echo "service_env=['Test','Integration']" >> $env:GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs:
      - setenv
    strategy:
      fail-fast: false
      matrix:
        env: ${{ fromJSON(needs.setenv.outputs.service_env) }}
    environment: ${{ matrix.env }}
    env:
      ENV_NAME: ${{ vars.ENV_NAME }}
    steps:
      - name: build
        run: |
          ls
          cd ./Docker
          docker build -t ${{ env.ENV_NAME }}:latest .
  # environ:
  #   needs: build
  #   runs-on: windows-latest
  #   environment: ${{ needs.build.outputs.channel }}
  #   env:
  #       ENV_NAME: ${{ vars.ENV_NAME }}
  #   steps:
  #   - name: echo
  #     run: |
  #       echo ${{ needs.build.outputs.channel }}
  #       echo "${{ env.ENV_NAME }}"
        